import os

API_KEY = "91ZN13cCtvBzMwLNvYnvnhmFFnSueHPijXg7ZSuKC46EjzECaZXh740ZoOQ7Es2I"
API_SECRET = "KZ4zpmrtGqHEz7HYjyuJ0z6uxfbc7DVoKaFVpBFGDXV6g9BeEtlvCJQt68h7qZQW"

BASE_URL = "https://fapi.binance.com"
REQUEST_TIMEOUT = 5
API_RETRY = 3

USE_PAPER_TRADING = False

SYMBOLS = [
    "ETHUSDT",
    "SOLUSDT",
    "DOGEUSDT",
]

TIMEFRAME = "1m"

# ================= CAPITAL =================
INITIAL_CAPITAL = 31.36043272
LEVERAGE = 8

MAX_POSITIONS = 1
CAPITAL_PER_TRADE = 0.12
MAX_POSITION_SIZE = 0.28
MAX_DAILY_TRADES = 50

# ================= RISK =================
MAX_DAILY_LOSS = 0.03
MAX_DRAWDOWN = 0.08

STOP_LOSS = 0.006
TAKE_PROFIT = 0.014

MAX_CONSECUTIVE_LOSSES = 4

# ================= ORDER =================
ORDER_TYPE = "AUTO"
SLIPPAGE_LIMIT = 0.0135
MAX_ORDER_RETRY = 2
ALLOW_PARTIAL_FILL = True

# ================= FEATURE =================
ENABLE_ORDERFLOW_PRESSURE = True
ENABLE_LIQUIDITY_SWEEP = True
ENABLE_VOLATILITY_BREAKOUT = True

ENABLE_ALPHA = True
ENABLE_MTF = False
ENABLE_ARBITRAGE = False

# ================= LOG =================
LOG_LEVEL = "INFO"
LOOP_INTERVAL = 1
DATA_CACHE_SECONDS = 1

MAX_LATENCY_MS = 300
HEARTBEAT_INTERVAL = 10

LOG_TRADES = True
LOG_ERRORS = True
LOG_PERFORMANCE = True

# ================= SYMBOL =================
DEFAULT_SYMBOL_LEVERAGE = 5
MIN_SIGNAL_INTERVAL_SECONDS = 8
SYMBOL_REENTRY_COOLDOWN_SECONDS = 18.0
SYMBOL_FLIP_COOLDOWN_SECONDS = 28.0

MAX_SPREAD_RATIO = 0.0018
STALE_BOOK_SECONDS = 1.0

# ================= MICRO =================
MICRO_WINDOW_SECONDS = 6.0
MICRO_IMBALANCE_THRESHOLD = 1.06
MICRO_MIN_TOTAL_FLOW = 3.5
MICRO_MIN_TRADE_COUNT = 20
MICRO_MIN_NET_FLOW_RATIO = 0.18

MICRO_SIGNAL_COOLDOWN_SECONDS = 8.0
MICRO_SAME_SIDE_REARM_SECONDS = 2.6
MICRO_OPPOSITE_SIDE_CONFIRM_RATIO = 1.04

MICRO_RESET_ON_SIGNAL = False
MICRO_MAX_STORED_TRADES = 2000

# ================= PRESSURE =================
PRESSURE_WINDOW_SECONDS = 4.0
PRESSURE_RATIO = 1.10
PRESSURE_MIN_TOTAL_VOLUME = 1.0
PRESSURE_MIN_TRADE_COUNT = 3
PRESSURE_MIN_NET_VOLUME_RATIO = 0.08
PRESSURE_MIN_AVG_TRADE_SIZE_RATIO = 0.84

PRESSURE_SIGNAL_COOLDOWN_SECONDS = 1.0
PRESSURE_SAME_SIDE_REARM_SECONDS = 1.9
PRESSURE_OPPOSITE_SIDE_CONFIRM_RATIO = 1.05

PRESSURE_MAX_STORED_TRADES = 4000

# ================= VELOCITY =================
VELOCITY_WINDOW_SECONDS = 3.0
VELOCITY_THRESHOLD = 2.0
VOLUME_VELOCITY_THRESHOLD = 18.0

VELOCITY_MIN_TOTAL_TRADES = 4.0
VELOCITY_MIN_TOTAL_VOLUME = 35.0
VELOCITY_MIN_SIDE_SHARE = 0.55
VELOCITY_MIN_NET_VOLUME_RATIO = 0.08

VELOCITY_SIGNAL_COOLDOWN_SECONDS = 2.2
VELOCITY_SAME_SIDE_REARM_SECONDS = 4.8
VELOCITY_OPPOSITE_SIDE_CONFIRM_RATIO = 1.06

VELOCITY_MAX_STORED_TRADES = 4000

# ================= VOL =================
VOL_WINDOW_SECONDS = 10.0
VOL_MIN_SAMPLES = 6
VOL_MIN_VALUE = 0.00020
VOL_MAX_VALUE = 0.018
VOL_SHOCK_VALUE = 0.018

VOL_MAX_STORED_POINTS = 4000

# ================= ALPHA =================
ALPHA_BUY_THRESHOLD = 0.58
ALPHA_SELL_THRESHOLD = 0.58
ALPHA_MIN_AGREE_COUNT = 2

ALPHA_SIGNAL_COOLDOWN_SECONDS = 9
ALPHA_SAME_SIDE_REARM_SECONDS = 2.8
ALPHA_FLIP_BLOCK_SECONDS = 4.8
ALPHA_STRONG_FLIP_MULTIPLIER = 1.12

# ================= IMBALANCE =================
IMBALANCE_THRESHOLD = 1.03
IMBALANCE_MIN_RATIO = 0.045
IMBALANCE_MAX_RATIO = 4.0
IMBALANCE_MIN_LIQUIDITY = 35.0

IMBALANCE_TOP_LEVELS = 5
IMBALANCE_HISTORY_SECONDS = 2.0
IMBALANCE_MIN_HISTORY_POINTS = 3
IMBALANCE_MIN_PERSISTENCE_RATIO = 0.55

IMBALANCE_COOLDOWN_SECONDS = 2.4
IMBALANCE_SAME_SIDE_REARM_SECONDS = 4.0
IMBALANCE_FLIP_BLOCK_SECONDS = 6.0
IMBALANCE_STRONG_FLIP_MULTIPLIER = 1.12

IMBALANCE_STALE_BOOK_SECONDS = 1.0
IMBALANCE_MAX_HISTORY_POINTS = 200

# ================= FILTER =================
FILTER_MIN_SCORE = 0.32
FILTER_MIN_CONFIDENCE = 0.30

FILTER_ACCEPT_COOLDOWN_SECONDS = 0.90
FILTER_REJECT_COOLDOWN_SECONDS = 0.20

# ================= REGIME =================
REGIME_WINDOW_SECONDS = 20.0
REGIME_MIN_SAMPLES = 3

REGIME_TREND_RATIO_THRESHOLD = 0.515
REGIME_SHOCK_RATIO_THRESHOLD = 0.0032
REGIME_CHOP_BAND_THRESHOLD = 0.007

# ================= POSITION =================
POSITION_MIN_HOLD_SECONDS = 8.0
POSITION_REENTRY_COOLDOWN_SECONDS = 18.0
POSITION_FLIP_COOLDOWN_SECONDS = 28.0

POSITION_EXECUTION_LOCK_SECONDS = 1.6
POSITION_MIN_SIZE = 0.001

# ================= SIZING =================
SIZING_EXCHANGE_MIN_NOTIONAL = 2.0

SIZING_MIN_SIGNAL_MULTIPLIER = 0.8
SIZING_MAX_SIGNAL_MULTIPLIER = 1.8

SIZING_MIN_VOLATILITY_FLOOR = 0.0005
SIZING_MAX_VOLATILITY_CAP = 0.08

SIZING_MAX_MARGIN_USAGE_RATIO = 0.85
SIZING_FREE_BALANCE_BUFFER_RATIO = 0.05

# ================= EXECUTION =================
EXECUTOR_MIN_ORDER_INTERVAL_SECONDS = 3.5
EXECUTOR_SYMBOL_LOCK_SECONDS = 5.0

EXECUTOR_RETRY_ATTEMPTS = 2
EXECUTOR_RETRY_SLEEP_SECONDS = 0.25

EXECUTOR_QTY_PRECISION = 3
EXECUTOR_MIN_QTY = 0.0001

ROUTER_MIN_ORDER_INTERVAL_SECONDS = 1.2
ROUTER_SAME_SIDE_COOLDOWN_SECONDS = 2.0

# ================= SYNC =================
POSITION_SYNC_INTERVAL_SECONDS = 3

# ================= VALIDATION =================
if not USE_PAPER_TRADING:
    if not API_KEY or not API_SECRET:
        raise Exception("API KEY REQUIRED")